name: mediar
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - ca-certificates
  - ld_impl_linux-64=2.40
  - libffi
  - libgcc-ng
  - libgomp
  - libstdcxx-ng
  - ncurses
  - openssl
  - pip=25.0
  - python=3.9.21
  - readline=8.2
  - setuptools=75.8.0
  - sqlite
  - tk
  - wheel=0.45.1
  - xz
  - zlib
  - pip:
      - appdirs==1.4.4
      - certifi==2025.4.26
      - charset-normalizer==3.4.1
      - click==8.1.8
      - contourpy==1.3.0
      - cycler==0.12.1
      - docker-pycreds==0.4.0
      - efficientnet-pytorch==0.7.1
      - fastremap==1.14.1
      - filelock==3.18.0
      - fonttools==4.57.0
      - fsspec==2025.3.2
      - gitdb==4.0.12
      - gitpython==3.1.44
      - huggingface-hub==0.30.2
      - idna==3.10
      - imagecodecs==2024.12.30
      - imageio==2.37.0
      - importlib-resources==6.5.2
      - jinja2==3.1.6
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - llvmlite==0.40.1
      - markupsafe==3.0.2
      - matplotlib==3.9.4
      - monai==1.3.0
      - mpmath==1.3.0
      - munch==4.0.0
      - networkx==3.2.1
      - numba==0.57.1
      - numpy==1.24.3
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.1.105
      - packaging==25.0
      - pandas==2.0.3
      - pillow==11.2.1
      - pretrainedmodels==0.7.4
      - protobuf==4.25.7
      - psutil==7.0.0
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytz==2023.3.post1
      - pyyaml==6.0.2
      - requests==2.32.3
      - safetensors==0.5.3
      - scikit-image==0.24.0
      - scipy==1.12.0
      - segmentation-models-pytorch==0.3.3
      - sentry-sdk==2.27.0
      - setproctitle==1.3.5
      - six==1.17.0
      - smmap==5.0.2
      - sympy==1.14.0
      - tifffile==2023.4.12
      - timm==0.9.2
      - torch==2.1.2
      - torchvision==0.16.2
      - tqdm==4.65.0
      - triton==2.1.0
      - typing-extensions==4.13.2
      - tzdata==2025.2
      - urllib3==2.4.0
      - wandb==0.16.2
      - zipp==3.21.0
